"""create devices and loans tables

Revision ID: 6f13097d5c18
Revises: eaf5bb584fec
Create Date: 2026-09-25 13:20:06.354556
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '6f13097d5c18'
down_revision: Union[str, Sequence[str], None] = 'eaf5bb584fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###