"""create devices and loans tables

Revision ID: eaf5bb584fec
Revises: 0001_initial
Create Date: 2026-09-25 13:16:22.245118
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'eaf5bb584fec'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    # ### end Alembic commands ###